// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zughhzyowlmdsyhvvnop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1Z2hoenlvd2xtZHN5aHZ2bm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NzgyODcsImV4cCI6MjA2NTM1NDI4N30.EHZLXN73tresM5bCbDXzgMpipDJGtxqXgaAazXRqHOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);